import type { pt } from './pt';

export const en: typeof pt = {
  loader: { skip: 'Continue to the site', label: 'Loading the portfolio', progress: 'Getting ready: {{count}}%' },
  meta: { title: 'João Victor Fonseca — Development & expression', description: 'Full Stack Developer based in Londrina, Brazil. Code, visual craft and digital experiences. Explore João Victor Fonseca’s work.' },
  brand: { initials: '/icon.png', name: 'João Victor Fonseca', shortName: 'João Victor', surname: 'Fonseca' },
  nav: { label: 'Main navigation', work: 'Experience', about: 'About', contact: 'Say hello', skip: 'Skip to content', home: 'Back to home', language: 'Website language', portuguese: 'Switch to Portuguese', english: 'Switch to English', pt: 'PT', en: 'EN' },
  hero: { eyebrow: 'DEVELOPMENT × EXPRESSION', line1: 'Logic.', line2: 'Form.', line3: 'Motion.', intro: 'I’m João Victor. A Full Stack Developer with an eye shaped by art.', detail: 'I turn complexity into digital experiences that make sense — and engage the senses.', cta: 'Explore my work', availability: 'Open to opportunities', location: 'LONDRINA, BRAZIL', scroll: 'KEEP EXPLORING', edition: 'PORTFOLIO / 2026' },
  scene: { label: 'Animated 3D Mickey. Drag or use the left and right arrow keys to rotate. Press Enter or space to pause or resume.', hint: 'Drag to rotate · or use the arrow keys', number: 'CODE IN MOTION', loading: 'Getting the character ready', fallback: 'The character could not be loaded.', retry: 'Try again', paused: 'Resume animation', playing: 'Pause animation', reset: 'Reset position', credit: 'Model adapted from', author: 'Adrian Cojocaru', license: 'CC BY 4.0' },
  work: { title: 'Code in the real world.', intro: 'Products, people and real problems. My experience.', current: 'CURRENT', more: 'View experience', less: 'Close details', stack: 'TECHNOLOGIES', items: [
    { company: 'Carga Online', type: 'WEB + MOBILE', role: 'Full Stack Developer', date: 'MAR 2026 — PRESENT', title: 'Connecting the whole operation.', description: 'Building an application for managing fleets, trucks and drivers. From back end to interface, with a focus on clear workflows and maintainable software.', details: 'Working across front end, back end and mobile to bring business rules and operational needs into a consistent experience.', stack: ['TypeScript', 'React', 'AdonisJS', 'PostgreSQL', 'React Native'] },
    { company: 'X-Brain', type: 'FRONT END', role: 'Junior Front-end Developer', date: 'APR 2025 — FEB 2026', title: 'Turning complexity into clarity.', description: 'Front-end development for Claro sales platform. Translating requirements and business rules into responsive, usable interfaces.', details: 'Collaborating on iterative releases, code reviews and product maintenance using React, JavaScript and Redux.', stack: ['React', 'JavaScript', 'Redux', 'CSS'] },
    { company: 'X-Brain', type: 'WEB DEVELOPMENT', role: 'Web Development Intern', date: 'AUG 2024 — MAR 2025', title: 'Learning by building.', description: 'Beginning my professional development career, contributing to the front end of Claro sales platform.', details: 'Taking part in projects, code reviews and practical learning alongside the development team.', stack: ['React', 'JavaScript', 'Redux', 'CSS'] }
  ] },
  about: { title1: 'Before the code,', title2: 'the eye.', lead: 'My first canvas was for painting.', paragraph1: 'Before building digital products, I taught digital painting at Escola Imago. Composition, hierarchy and attention to detail still shape the way I approach every interface.', paragraph2: 'Today I work across front end, back end and mobile. My next chapter brings development and visual expression even closer, creating experiences as a creative developer.', education: 'EDUCATION', degree: 'Systems Analysis and Development', school: 'Universidade Positivo · Londrina, Brazil', languages: 'LANGUAGES', languageList: 'Native Portuguese · English B2 · German A2', stack: 'MY TOOLKIT', groups: [{ title: 'Interfaces', items: 'React / Next.js / TypeScript / Redux / Vite / Three.js / WebGL / GSAP' }, { title: 'Systems', items: 'Node.js / AdonisJS / Nest.js / PostgreSQL' }, { title: 'Mobile', items: 'React Native / Flutter' }], art: 'ART', code: 'CODE', connection: 'Two languages. One perspective.', pdf: 'My portfolio in PDF', years: '2+', yearsLabel: 'YEARS OF EXPERIENCE', areas: '3', areasLabel: 'WEB, BACK END & MOBILE' },
  contact: { cursorCredit: 'Cursor by NaLexnu', title: 'Say hello.', channels: 'Where to find me', email: 'jotaafon@gmail.com', copy: 'Copy email', copied: 'Email copied', copyError: 'Could not copy. Please use the email link.', linkedin: 'LinkedIn', github: 'GitHub', gmail: 'Gmail', whatsapp: 'WhatsApp', githubDetail: 'Explore my code', gmailDetail: 'Send an email', linkedinDetail: 'Let’s connect', whatsappDetail: 'Start a conversation', footer: 'Made with code, curiosity and intention.', top: 'Back to top', copyright: '© {{year}} João Victor Fonseca', remote: 'Londrina, Brazil · Open to remote work' }
};
