export const pt = {
  meta: { title: 'João Victor Fonseca — Desenvolvimento & expressão', description: 'Desenvolvedor Full Stack em Londrina. Código, sensibilidade visual e experiências digitais. Conheça a trajetória de João Victor Fonseca.' },
  brand: { initials: 'jf', name: 'João Victor Fonseca', shortName: 'João Victor', surname: 'Fonseca' },
  nav: { label: 'Navegação principal', work: 'Trajetória', about: 'Sobre', contact: 'Vamos conversar', skip: 'Pular para o conteúdo', home: 'Voltar ao início' },
  hero: { eyebrow: 'DESENVOLVIMENTO × EXPRESSÃO', line1: 'Lógica.', line2: 'Forma.', line3: 'Movimento.', intro: 'Sou João Victor. Desenvolvedor Full Stack com um olhar que vem da arte.', detail: 'Transformo complexidade em experiências digitais que fazem sentido — e despertam os sentidos.', cta: 'Explore meu trabalho', availability: 'Aberto a oportunidades', location: 'LONDRINA, BRASIL', scroll: 'CONTINUE EXPLORANDO', edition: 'PORTFÓLIO / 2026' },
  scene: { label: 'Escultura digital interativa. Arraste para girar ou use as setas do teclado.', hint: 'ARRASTE PARA EXPLORAR', number: 'ESTUDO 001 — FLUXO', loading: 'Preparando a experiência', fallback: 'Lógica encontra forma.', material: 'Mudar material da escultura', chrome: 'Cromo', blue: 'Azul', paused: 'Retomar movimento', playing: 'Pausar movimento', reset: 'Restaurar posição' },
  work: { label: '01 / TRAJETÓRIA', title: 'Código no mundo real.', intro: 'Produtos, pessoas e problemas reais. Minha experiência construindo soluções de ponta a ponta.', current: 'ATUAL', more: 'Ver atuação', less: 'Fechar detalhes', stack: 'TECNOLOGIAS', items: [
    { company: 'Carga Online', type: 'WEB + MOBILE', role: 'Desenvolvedor Full Stack', date: 'MAR 2026 — ATUAL', title: 'Conectando toda a operação.', description: 'Desenvolvimento de uma aplicação para gerenciamento de frotas, caminhões e caminhoneiros. Do back-end à interface, com atenção à clareza dos fluxos e à manutenção do produto.', details: 'Atuação em front-end, back-end e mobile, integrando regras de negócio e necessidades operacionais em uma experiência consistente.', stack: ['TypeScript', 'React', 'AdonisJS', 'PostgreSQL', 'React Native'] },
    { company: 'X-Brain', type: 'FRONT-END', role: 'Desenvolvedor Front-end Junior', date: 'ABR 2025 — FEV 2026', title: 'Complexidade vira clareza.', description: 'Desenvolvimento do front-end do sistema de vendas da Claro. Requisitos e regras de negócio traduzidos em interfaces responsivas e usáveis.', details: 'Colaboração em entregas iterativas, revisões de código e manutenção dos fluxos do produto, com React, JavaScript e Redux.', stack: ['React', 'JavaScript', 'Redux', 'CSS'] },
    { company: 'X-Brain', type: 'DESENVOLVIMENTO WEB', role: 'Estagiário de Desenvolvimento Web', date: 'AGO 2024 — MAR 2025', title: 'A base se constrói fazendo.', description: 'Início da trajetória profissional em desenvolvimento, apoiando o front-end do sistema de vendas da Claro.', details: 'Participação na rotina de projetos, revisões de código e aprendizado aplicado com o time de desenvolvimento.', stack: ['React', 'JavaScript', 'Redux'] }
  ] },
  about: { label: '02 / SOBRE MIM', title1: 'Antes do código,', title2: 'o olhar.', lead: 'Minha primeira tela era uma tela de pintura.', paragraph1: 'Antes de desenvolver produtos digitais, ensinei pintura digital na Escola Imago. Composição, hierarquia e atenção aos detalhes continuam fazendo parte de como penso cada interface.', paragraph2: 'Hoje, atuo em front-end, back-end e mobile. Meu próximo capítulo é aproximar ainda mais desenvolvimento e expressão visual, criando experiências como creative developer.', education: 'FORMAÇÃO', degree: 'Análise e Desenvolvimento de Sistemas', school: 'Universidade Positivo · Londrina, PR', languages: 'IDIOMAS', languageList: 'Português nativo · Inglês B2 · Alemão A2', stack: 'MEU REPERTÓRIO', groups: [{ title: 'Interfaces', items: 'React / Next.js / TypeScript / Redux / Vite / Three.js / WebGL / GSAP' }, { title: 'Sistemas', items: 'Node.js / AdonisJS / Nest.js / PostgreSQL' }, { title: 'Mobile', items: 'React Native / Flutter' }], art: 'ARTE', code: 'CÓDIGO', connection: 'Duas linguagens. O mesmo olhar.', pdf: 'Meu portfólio em PDF', years: '2+', yearsLabel: 'ANOS DE EXPERIÊNCIA', areas: '3', areasLabel: 'WEB, BACK-END E MOBILE' },
  contact: { label: '03 / CONTATO', title1: 'Boas ideias', title2: 'começam com um oi.', text: 'Tem um projeto em mente ou uma oportunidade para compartilhar? Vamos conversar.', email: 'jotaafon@gmail.com', copy: 'Copiar e-mail', copied: 'E-mail copiado', copyError: 'Não foi possível copiar. Use o link de e-mail.', linkedin: 'LinkedIn', github: 'GitHub', footer: 'Feito de código, curiosidade e intenção.', top: 'Voltar ao topo', copyright: '© {{year}} João Victor Fonseca', remote: 'Londrina, PR · Aberto a trabalho remoto' }
};
